### ISSUE TITLE
NLP Task Reproduction Unsuccessful

### ISSUE THREAD

**Issue by LQF39466** [DaShenZi721/HRA#4]
I followed the steps in your README to reproduce results on SST2 dataset. While installing dependencies pip could not find the 0.1.13 version of DeBERTa. I cloned the official DeBERTa repository and packed it using wheels by myself. 

I was able to run the sst2.sh script successfully, yet the experimental results had very poor accuarcy during evaluation. It would seem your experiment script used my compiled version of DeBERTa's `run.py` instead of yours in the HRA repository, hence adapters didn't seem to be loaded. (final output as attached below)
[eval_results_dev_deberta-v3-base.txt](https://github.com/user-attachments/files/17359683/eval_results_dev_deberta-v3-base.txt)

I would like to know is there anything you haven't mentioned in your README that could cause this. Thank you.

**Comment by DaShenZi721** [comment]
Thanks for your appreciation of our work! 
For your first question, did you run the command `python setup.py install`? After any modification to the codes, you need to run this command.
For the second question, you can check this scripts [disentangled_attention.py](https://github.com/DaShenZi721/HRA/blob/master/nlu/DeBERTa/deberta/disentangled_attention.py) and [bert.py](https://github.com/DaShenZi721/HRA/blob/master/nlu/DeBERTa/deberta/bert.py)  where we inject HRA adapters.

**Comment by LQF39466** [comment]
Thank you very much for your reply! I have one more question regarding the name "householder_u" you used when calculating loss in [trainer.py](https://github.com/DaShenZi721/HRA/blob/8bfc9b0cfbdd9d8b670660bb660bb99cd5373665/nlu/DeBERTa/training/trainer.py#L245) file. I have not been able to locate any relevant definition of this name, so I was wondering how the name is being generated and obtained.

**Comment by DaShenZi721** [comment]
Sorry, we uploaded the wrong version earlier, it has now been corrected.

In addition, this code corresponds to the orthogonality regularizer in the loss, which might reduce runtime efficiency. It's just fine to comment it out.

https://github.com/DaShenZi721/HRA/blob/be25c7f46ac6bb26a8a75e36395938441c192a44/nlu/DeBERTa/training/trainer.py#L244-L249

**Comment by LQF39466** [comment]
I see no `setup.py` file in `/nlu`, is this normal?

**Comment by DaShenZi721** [comment]
We just uploaded `setup.py`.

**Comment by LQF39466** [comment]
I have successfully run the experiment and got satisfactory results. Thank you very much!
