### ISSUE TITLE
Certain GLUE results are abnormal

### ISSUE THREAD

**Issue by LQF39466** [DaShenZi721/HRA#5]
I have been experimenting with GLUE datasets and have not achieved the expected results on the `COLA`, `RTE`, and `MRPC` datasets. I have double-checked my training configuration and ensured that I adhered to the hyperparameters suggested in your paper. Nevertheless, the metrics for these tasks display unusual behavior during the training process.

Training logs are attached as follows. 

[training_MRPC.log](https://github.com/user-attachments/files/17532619/training_MRPC.log)
[training_RTE.log](https://github.com/user-attachments/files/17532620/training_RTE.log)
[training_CoLA.log](https://github.com/user-attachments/files/17532621/training_CoLA.log)

I would like to know what could have caused this and is there a fix or workaround reguarding this problem.

**Comment by LQF39466** [comment]
Another problem running `STS-B`，during training the metric turned into `nan`.

Training log attached.

[Uploading training_STS-B.log…]()

**Comment by DaShenZi721** [comment]
We just updated the hyperparameters. You could give it a try.
